kind: Service
apiVersion: v1
metadata:
  name: neymar
  namespace: farag3
  labels:
    app: hello-openshift
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    
  selector:
    app: hello-openshift
  type: ClusterIP
  sessionAffinity: None
