kind: Service
apiVersion: v1
metadata:
  name: example
spec: 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
 selector:
    app: hello-openshift
 type: ClusterIP
 sessionAffinity: None
  
