apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql13
  namespace: farag3
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-cephfs

