kind: PersistentVolumeClaim
apiVersion: v1

  namespace: farag3
 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem



