kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql
  namespace: farag3
 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2

