apiVersion: route.openshift.io/v1
kind: Route
metadata:
  namespace: farag3
  labels:
    app: hello-openshift
  name: hello-openshift
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: example
    weight: 100
